site_name: James' Thesis
theme:
  name: gitbook
  logo: pix/selfprotrait.svg
  favicon: pix/selfprotrait.svg
nav:
  - index.md
  - Introductrion:
    - 'contributing.md'
    - 'overview.md'
    - 'aims.md'
    - 'herbicide-resistance.md'
    - 'enzyme-engineering.md'
    - 'p450s.md'
    - 'protein-structure-pred.md'
    - 'docking.md'
    - 'deep-learning.md'
    - 'hts.md'
    - 'rio-outline.md'
    - 'evo-outline.md'
  - Methods:
    - 'methods-general.md'
    - 'methods-rio.md'
    - 'methods-evo.md'
    - 'enz.md'
  - Results:
    - 'results-evo.md'
    - 'results-rio.md'


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - mdx_math
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - smarty

plugins:
  - bibtex:
      bib_file: "refs.bib"
      cite_style: "pandoc"
      bib_command: \bib
