site_name: James' Thesis
site_favicon: pix/selfportrait.svg
theme:
  name: gitbook
nav:
  - index.md
  - 'contributing.md'
  - Overlap:
    - 'overview.md'
    - 'herbicide-resistance.md'
    - 'enzyme-engineering.md'
    - 'mesotrione.md'
    - 'p450s.md'
    - 'bm3.md'
    - 'aims.md'
    - 'methods-general.md'
  - Paper 1:
    - 'intro-evo.md'
    - 'protein-structure-pred.md'
    - 'docking.md'
    - 'molecular-dynamics.md'
    - 'evo-outline.md'
    - 'methods-evo.md'
    - 'results-evo.md'
    - 'discussion-evo.md'
  - Paper 2:
    - 'intro-rio.md'
    - 'deep-learning.md'
    - 'hts.md'
    - 'rio-outline.md'
    - 'methods-rio.md'
    - 'results-rio.md'
    - 'discussion-rio.md'
  - Appendix:
    - 'enz.md'
    - 'mxn.md'
    - 'cpd.md'
    - 'echo.md'
    - 'plates.md'
  - References:
    - 'references.md'

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - mdx_math
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - smarty

plugins:
  - bibtex:
      bib_file: "refs.bib"
      cite_style: "pandoc"
      bib_command: \bib
