site_name: Thesis 
repo_url: https://github.com/jamesengleback/thesis

theme:
  name: gitbook
  font:
    text: Noto Sans
    code: Noto Sans Mono

nav:
  - General:
    - index.md
    - general-overview.md
    - general-ai.md
    - general-directed-evolution.md
    - general-docking.md
    - general-hppds.md
    - general-p450s.md
    - general-protein-structure-prediction.md
  - Screening Fist:
    - sxfst-introduction.md
    - sxfst-methods.md
    - sxfst-results.md
    - sxfst-discussion.md
    - sxfst-appendix.md
  - Virtual Directed Evolution:
    - vde-introduction.md
    - vde-methods.md
    - vde-results.md
    - vde-discussion.md

markdown_extensions:
  - mdx_math
  - footnotes
  - attr_list
  - md_in_html
  - toc
  - smarty
  - admonition
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
          #format: !!python/name:mermaid2.fence_mermaid

extra_css:
  - https://unpkg.com/mermaid@7.1.2/dist/mermaid.css
extra_javascript:
  - https://unpkg.com/mermaid@7.1.2/dist/mermaid.min.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js



plugins:
  - bibtex:
      bib_file: "refs.bib"
      cite_style: "pandoc"
      bib_command: \bib
  - mermaid2:
      arguments:
              theme: 'neutral'

